version: "3.3"

services:
  app:
    build:
      context: ./app
    ports:
      - "8089:8089"
    networks:
      - go_app_network
  
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    networks:
      - go_app_network
  
  nginx:
    
    build:
      context: ./nginx
      
    ports:
      - 80:80
  
    networks:
      - "go_app_network"
    depends_on:
      - redis
  
networks:
  go_app_network:
    name: "go_app"
    driver: "bridge"

